export interface ServiceItem {
  id: string;
  category: "har" | "fransar" | "hijab" | "special";
  categoryLabel: string;
  title: string;
  duration: string;
  price: string;
  priceValue?: number;
  description: string;
  features?: string[];
  image?: string;
  bookingUrl: string;
  badge?: string;
}

export const servicesCategories = [
  { key: "alla", label: "Alla behandlingar" },
  { key: "har", label: "Hårbehandlingar (Frisör)" },
  { key: "fransar", label: "Fransar & Bryn (Stylist)" },
  { key: "hijab", label: "Hijab-anpassat" },
] as const;

export const defaultBokadirektUrl = "https://www.bokadirekt.se/places/studio-corner-137505";

export const topFeaturedServiceIds = [
  "klippning",
  "balayage-mellan",
  "farg-klipp",
  "combo-klassisk",
  "koreansk-lashlift",
  "brow-lift",
];

export const servicesData: ServiceItem[] = [
  // --- HÅRBEHANDLINGAR (Frisör Azra) ---
  {
    id: "klippning",
    category: "har",
    categoryLabel: "Klippning",
    title: "Klippning med styling",
    duration: "90 min",
    price: "660 kr",
    priceValue: 660,
    description: "Komplett damklippning anpassad efter din hårtyp, ansiktsform och personliga önskemål. Avslutas med vårdande styling.",
    features: ["Konsultation ingår", "Tvätt och hårvård", "Professionell fön och styling"],
    image: "/images/hair-treatment.jpg",
    bookingUrl: defaultBokadirektUrl,
    badge: "Populärast",
  },
  {
    id: "quick-fix-face-frame",
    category: "har",
    categoryLabel: "Slingor",
    title: "QUICK FIX – Face frame / bena / hårfäste",
    duration: "90 min",
    price: "Från 1 150 kr",
    priceValue: 1150,
    description: "En snabb och effektiv lösning för att fräscha upp håret kring ansiktet eller benan mellan dina större färgbehandlingar.",
    features: ["Ljusar upp konturerna", "Skonsam uppfräschning", "Perfekt underhåll"],
    image: "/images/hair-treatment.jpg",
    bookingUrl: defaultBokadirektUrl,
  },
  {
    id: "balayage-kort",
    category: "har",
    categoryLabel: "Slingor & Balayage",
    title: "Slingor / Balayage – Kort till axellångt hår",
    duration: "210 min",
    price: "Från 1 600 kr",
    priceValue: 1600,
    description: "Skräddarsydd slingbehandling eller balayageteknik för mjuk, dimensionell färg och naturliga övergångar på kortare till axellångt hår.",
    features: ["Naturliga övergångar", "Individuell nyansering", "Lång hållbarhet"],
    image: "/images/hair-treatment.jpg",
    bookingUrl: defaultBokadirektUrl,
  },
  {
    id: "balayage-mellan",
    category: "har",
    categoryLabel: "Slingor & Balayage",
    title: "Slingor / Balayage – Axellångt till brösthöjd",
    duration: "230 min",
    price: "Från 1 900 kr",
    priceValue: 1900,
    description: "Avancerad frihandsteknik och folieslingor för halvlångt hår som ger lyster, liv och djup.",
    features: ["Djup & dimension", "Skonsam blekning", "Glansgivande finish"],
    image: "/images/hair-treatment.jpg",
    bookingUrl: defaultBokadirektUrl,
    badge: "Mest bokad",
  },
  {
    id: "balayage-langt",
    category: "har",
    categoryLabel: "Slingor & Balayage",
    title: "Slingor / Balayage – Brösthöjd till extra långt",
    duration: "230 min",
    price: "Från 2 100 kr",
    priceValue: 2100,
    description: "För dig med extra långt eller tjockt svall. Noggrann sektionering och färgplacering för maximal lyster och felfria slingor.",
    features: ["Full täckning och lyster", "Premium hårvård ingår", "Mjuk utväxtlinje"],
    image: "/images/hair-treatment.jpg",
    bookingUrl: defaultBokadirektUrl,
  },
  {
    id: "klipp-nyansering",
    category: "har",
    categoryLabel: "Färgning",
    title: "Klipp & Nyansering",
    duration: "150 min",
    price: "Från 1 000 kr",
    priceValue: 1000,
    description: "Återställer glans och neutraliserar oönskade varma toner i håret samtidigt som topparna klipps till perfektion.",
    features: ["Intensiv glans och lyster", "Färguppfräschning", "Toppklippning & fön"],
    image: "/images/hair-spa.jpg",
    bookingUrl: defaultBokadirektUrl,
  },
  {
    id: "farg-klipp",
    category: "har",
    categoryLabel: "Färgning",
    title: "Färgbehandling & Klipp – Grå hår / utväxt",
    duration: "150 min",
    price: "Från 1 000 kr",
    priceValue: 1000,
    description: "Klassisk bottenfärgning eller helfärg för effektiv gråhårstäckning eller utväxtfärgning, kombinerad med en personlig klippning.",
    features: ["100% gråhårstäckning", "Jämn och hållbar färg", "Klipp och vårdande finish"],
    image: "/images/hair-treatment.jpg",
    bookingUrl: defaultBokadirektUrl,
    badge: "Populär",
  },
  {
    id: "tvatt-fon",
    category: "har",
    categoryLabel: "Styling",
    title: "Tvätt & fön",
    duration: "60 min",
    price: "550 kr",
    priceValue: 550,
    description: "Njut av en avkopplande hårtvätt med hårbottenmassage och en lyxig föning som håller formen hela veckan eller inför festen.",
    features: ["Skön hårbottenmassage", "Volym & hållbarhet", "Perfekt inför helgen"],
    image: "/images/hair-spa.jpg",
    bookingUrl: defaultBokadirektUrl,
  },

  // --- FRANSAR & BRYN (Stylist Ema) ---
  {
    id: "klassisk-lashlift",
    category: "fransar",
    categoryLabel: "Fransar",
    title: "Klassisk LashLift",
    duration: "60 min",
    price: "400 kr",
    priceValue: 400,
    description: "Framhäv dina naturliga fransar! Lash Lift böjer och lyfter dina fransar från roten för ett längre, öppnare och piggare intryck. Avslutas med färgning. Resultatet håller ca 6–8 veckor.",
    features: ["Håller 6–8 veckor", "Fransfärgning ingår", "Skonsam mot naturliga fransar"],
    image: "/images/lashes-brows.jpg",
    bookingUrl: defaultBokadirektUrl,
    badge: "Kundfavorit",
  },
  {
    id: "koreansk-lashlift",
    category: "fransar",
    categoryLabel: "Fransar",
    title: "Koreansk Lashlift (Korean Technique)",
    duration: "65 min",
    price: "475 kr",
    priceValue: 475,
    description: "En skonsam lashlift-teknik som ger ett mer rakt och uppåtgående lyft. Perfekt för dig som har raka, nedåtriktade eller svårformade fransar och önskar ett naturligt men markant resultat. Hållbarhet: 6–8 veckor.",
    features: ["Optimal för raka/svårformade strån", "Rakt och högt lyft", "Innovativ koreansk teknik"],
    image: "/images/lashes-brows.jpg",
    bookingUrl: defaultBokadirektUrl,
    badge: "Trend",
  },
  {
    id: "brow-lift",
    category: "fransar",
    categoryLabel: "Bryn",
    title: "Brow Lift (Brynlaminering)",
    duration: "60 min",
    price: "380 kr",
    priceValue: 380,
    description: "Brynstråna formas och fixeras i önskad riktning för att skapa ett fylligare, jämnare och mer välvårdat utseende. Kombineras med formning och färgning. Håller 4–8 veckor.",
    features: ["Fylligare look direkt", "Skräddarsydd form", "Håller i 4–8 veckor"],
    image: "/images/lashes-brows.jpg",
    bookingUrl: defaultBokadirektUrl,
    badge: "Kundfavorit",
  },
  {
    id: "combo-klassisk",
    category: "fransar",
    categoryLabel: "Kombo-behandling",
    title: "COMBO – Klassisk Lashlift + Browlift",
    duration: "60 min",
    price: "550 kr",
    priceValue: 550,
    description: "Den ultimata blicken! Få både vackert böjda fransar och perfekt stylade bryn i en och samma tidseffektiva behandling.",
    features: ["Både fransar & bryn", "Maximalt prisvärd kombo", "Färgning & formning ingår"],
    image: "/images/lashes-brows.jpg",
    bookingUrl: defaultBokadirektUrl,
    badge: "Mest populär",
  },
  {
    id: "combo-koreansk",
    category: "fransar",
    categoryLabel: "Kombo-behandling",
    title: "COMBO – Koreansk Lashlift + Browlift",
    duration: "75 min",
    price: "650 kr",
    priceValue: 650,
    description: "Kombinera det precisa koreanska franslyftet med fylligt formande browlift för den mest moderna och kompletta ansiktsramen.",
    features: ["Koreansk lyftteknik", "Brynlaminering & färg", "75 minuter ren egentid"],
    image: "/images/lashes-brows.jpg",
    bookingUrl: defaultBokadirektUrl,
  },
  {
    id: "brynplock-formning",
    category: "fransar",
    categoryLabel: "Bryn",
    title: "Brynplock / Formning",
    duration: "30 min",
    price: "150 kr",
    priceValue: 150,
    description: "Varsam uppfräschning och formning av dina bryn med pincett för en ren, definierad linje anpassad efter dina ansiktsdrag.",
    features: ["Snabb uppfräschning", "Skarp och ren linje"],
    image: "/images/lashes-brows.jpg",
    bookingUrl: defaultBokadirektUrl,
  },
  {
    id: "bryn-fargning",
    category: "fransar",
    categoryLabel: "Bryn",
    title: "Brynfärgning",
    duration: "20 min",
    price: "150 kr",
    priceValue: 150,
    description: "Färgning av brynen i en naturlig nyans som matchar din hudton och hårfärg för extra definition.",
    features: ["Naturlig definition", "Snabbt & hållbart"],
    image: "/images/lashes-brows.jpg",
    bookingUrl: defaultBokadirektUrl,
  },

  // --- HIJAB-ANPASSAT ---
  {
    id: "hijab-klippning",
    category: "hijab",
    categoryLabel: "Hijab-anpassat",
    title: "(Hijab) Klippning med styling",
    duration: "90 min",
    price: "660 kr",
    priceValue: 660,
    description: "En avskild, 100% insynsskyddad salongsmiljö enbart för kvinnor. Vår kvinnliga frisör tar hand om ditt hår med högsta precision och omtanke.",
    features: ["Enbart kvinnlig personal", "Helt insynsskyddad oas", "Klipp, tvätt och styling"],
    image: "/images/hair-treatment.jpg",
    bookingUrl: defaultBokadirektUrl,
    badge: "Trygg miljö",
  },
  {
    id: "hijab-farg-klipp",
    category: "hijab",
    categoryLabel: "Hijab-anpassat",
    title: "(Hijab) Färgbehandling & Klipp – grå hår / utväxt",
    duration: "150 min",
    price: "Från 1 000 kr",
    priceValue: 1000,
    description: "Färgning och klippning utförd i vår trygga salong för kvinnor. Lugn atmosfär och personlig service i Trollhättan.",
    features: ["Harmonisk miljö", "Kvalitetsfärger", "Total integritet"],
    image: "/images/hair-treatment.jpg",
    bookingUrl: defaultBokadirektUrl,
  },
  {
    id: "hijab-balayage",
    category: "hijab",
    categoryLabel: "Hijab-anpassat",
    title: "(Hijab) Slingor / Balayage – Olika längder",
    duration: "210 - 230 min",
    price: "Från 1 600 kr",
    priceValue: 1600,
    description: "Slingor och balayage i en bekväm, lugn och säker miljö där du kan slappna av fullständigt och njuta av din förvandling.",
    features: ["Skonsam behandling", "Personlig konsultation", "Full sekretess och trygghet"],
    image: "/images/hair-treatment.jpg",
    bookingUrl: defaultBokadirektUrl,
  },

  {
    id: "konsultation",
    category: "har",
    categoryLabel: "Rådgivning",
    title: "Personlig Konsultation",
    duration: "15 min",
    price: "0 kr (Kostnadsfri)",
    priceValue: 0,
    description: "Vi sätter oss ner i lugn och ro och går igenom dina önskemål, hårets skick, färg, längd och vilken metod som passar dig bäst.",
    features: ["Inga förbindelser", "Professionell expertis", "Skräddarsydd plan"],
    image: "/images/salon-interior.jpg",
    bookingUrl: defaultBokadirektUrl,
  },
];
